# Generated by Django 2.2.3 on 2019-07-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190727_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_group_admin',
            new_name='is_society_admin',
        ),
    ]
