# Generated by Django 2.2.3 on 2019-07-29 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190727_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(help_text="Designates the amount of money in the society's account.", verbose_name='Amount')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='The date the account was created.', verbose_name='Date')),
            ],
        ),
        migrations.AddField(
            model_name='society',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SocietyAccount'),
        ),
    ]
