# Generated by Django 2.2.3 on 2019-07-31 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='amount',
            field=models.IntegerField(default=0, help_text='Designates the amount of money credited to an account.', verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='society',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.SocietyAccount'),
        ),
        migrations.AlterField(
            model_name='society',
            name='description',
            field=models.CharField(help_text='A description of the society.', max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='society',
            name='maximum_capacity',
            field=models.IntegerField(help_text='Designates the maximum number people that can be in the society.', verbose_name='maximum capacity'),
        ),
        migrations.AlterField(
            model_name='society',
            name='name',
            field=models.CharField(help_text='Designates the name of the society.', max_length=150, unique=True, verbose_name='society name'),
        ),
        migrations.AlterField(
            model_name='societyaccount',
            name='balance',
            field=models.IntegerField(default=0, help_text="Designates the amount of money in the society's account.", verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Designates the date the tenure starts.', verbose_name='Tenure Start Date')),
                ('tentative_end_date', models.DateField(help_text='Designates the date a tenure will end if the maximum \t\t\t\tcapacity of the society has not been reached. It also \t\t\t\t\trepresents the last date a member can join the Esusu Society.', verbose_name='Tentative End Date')),
                ('maximum_end_date', models.DateField(help_text='Designates the date a tenure will end once the maximum \t\t\t\t\tcapacity of the society has been reached.', verbose_name='Maximum End Date')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_schedule', to='api.Society')),
            ],
            options={
                'verbose_name_plural': 'tenure',
            },
        ),
        migrations.CreateModel(
            name='CollectionSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(help_text='Designates the date that this user will be \t\t\t\teligible to collect the contribution from the society.', verbose_name='Collection Date')),
                ('tenure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_schedule', to='api.Tenure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'collection_schedules',
            },
        ),
    ]
